-- ---------------------------------------------------------------------------
-- 0026_figure_records.sql
--
-- Book 11.7 FIGURE RECORDS. Twenty-two records: the nineteen chapter figures
-- of Book 11.2, plus the three further devices that Chapter 1 conceals behind
-- its "etc." (Book 11.1 says the nineteen chapters hide roughly thirty to
-- thirty-five figures; the remaining thirteen live in each record's
-- sub_variants column, which is the hidden layer of Book 11.6 slot 4).
--
-- Every row carries BOTH FACES in the same record, as Book 11.7 requires:
-- legitimate_use and manipulative_misuse, plus detection_question for spotting
-- the figure inbound and overuse_tells for catching it in his own mouth.
--
-- No text from Farnsworth is reproduced here. These records are written from
-- standard classical-rhetoric reference knowledge; the book supplies the
-- syllabus (0025) and the page index (book_page_refs), not the prose.
--
-- Chapter slugs match migrations/0025_rhetoric_seed.sql exactly, including
-- chapter 1 = 'epizeuxis' and chapter 13 = 'praeteritio' (plain ASCII).
--
-- ROLLBACK (manual, additive migration, no schema change):
--   DELETE FROM figures WHERE slug IN (
--     'epizeuxis','epimone','conduplicatio','diacope','anaphora','epistrophe',
--     'symploce','anadiplosis','polyptoton','isocolon','chiasmus','anastrophe',
--     'polysyndeton','asyndeton','ellipsis','praeteritio','aposiopesis',
--     'metanoia','litotes','erotema','hypophora','prolepsis');
--   -- figure_own_examples and specimens reference figures(slug); delete or
--   -- re-point those rows FIRST if any exist, because D1 enforces foreign keys.
-- ---------------------------------------------------------------------------

-- ===========================================================================
-- PART I -- WHAT YOU DO TO WORDS.
-- ===========================================================================
INSERT OR IGNORE INTO figures (
  slug, canonical_name, classical_name, etymology, plain_definition,
  structural_formula, sub_variants, mechanism, part, chapter_id,
  conversational_job, rhetorical_effect, emotional_effect, legitimate_use,
  manipulative_misuse, detection_question, overuse_tells, related_figures,
  stackable_with, hidden_layer
) VALUES
  ('epizeuxis','Simple Repetition','epizeuxis (Greek: epi, upon + zeugnynai, to yoke)',
   'Greek epizeugnynai, a fastening together: the word yoked immediately to itself.',
   'The same word repeated at once, with nothing at all between the two instances.',
   'A A',
   'diacope (A x A, one small word intervening); epanalepsis (a clause opening and closing on the same word)',
   'A word repeated with no gap cannot be filed away as ordinary. The ear expects the sentence to move on; when it does not, the word is the only thing left to attend to.',
   1, 1,
   'When one word is the whole point and you want it to be the only thing carried out of the room.',
   'Concentrates the entire weight of the sentence on a single word.',
   'Urgency, or grief. It sounds like someone who has stopped arranging a sentence.',
   'A refusal or a boundary, where a fuller sentence would pad it into negotiability.',
   'Chanting a word until it feels agreed rather than argued: volume standing in for proof.',
   'Was the repeated word ever defined, or only repeated?',
   'Using it for ordinary emphasis; using it twice in one conversation. Both read as theatre, and being noticed is the failure condition.',
   'epimone,conduplicatio,diacope,anaphora',
   'asyndeton,aposiopesis',
   'Chapter 1 names simple repetition and then writes "etc." Concealed in that abbreviation are at least four separate devices -- epizeuxis, diacope, epimone, conduplicatio -- which are one move performed at four different distances.'),

  ('epimone','Persistent Repetition','epimone (Greek: epi, upon + monos, remaining)',
   'Greek epimone, a tarrying or persistence: staying on the point after the point has been made.',
   'A word or phrase returned to again and again across a passage, holding one idea in place while everything else moves.',
   'A ... A ... A (dispersed, one refrain)',
   'commoratio (dwelling on the same idea in changed words); refrain',
   'Anything the ear meets repeatedly at intervals becomes the frame the rest is heard inside. The refrain stops being an argument and becomes the ground.',
   1, 1,
   'When a single standard has to survive a long conversation that keeps trying to change the subject.',
   'Makes one idea the spine of a passage that ranges widely.',
   'Steadiness that shades into insistence.',
   'Holding one non-negotiable in view while genuinely discussing everything around it.',
   'Burying a weak claim under a phrase repeated so often that disagreement starts to feel like inattention.',
   'Is the refrain a standard I have accepted, or one I am being trained to accept?',
   'The listener can predict the phrase before it arrives. Once they can finish it for you, it is doing nothing.',
   'epizeuxis,conduplicatio,anaphora,symploce',
   'anaphora,isocolon',
   'Epimone is epizeuxis stretched across a passage instead of across two syllables. Recognising them as one mechanism at two distances is the hidden layer of Chapter 1.'),

  ('conduplicatio','Emphatic Restatement','conduplicatio (Latin: con, together + duplicare, to double)',
   'Latin conduplicatio, a doubling: the word taken up again in the next clause for emphasis.',
   'A word from one clause picked up and repeated in the next, near but not adjacent, to press on it.',
   'A ... , A ...',
   'ploce (the same word repeated with a shift of sense); antanaclasis (repeated with a genuinely different meaning)',
   'The near repetition signals that the speaker has noticed the word and chosen it, so the listener notices it too.',
   1, 1,
   'When you want to make a word the subject of the conversation without announcing that you are doing so.',
   'Promotes one word from a part of the sentence to the topic of the exchange.',
   'Deliberateness. It sounds like someone slowing down on purpose.',
   'Fixing the exact word that matters when a discussion has been sliding between near-synonyms.',
   'Repeating a loaded word until its worst sense becomes the accepted one, without ever defending that sense.',
   'Which of this word''s meanings am I being handed, and was it argued for?',
   'Every paragraph has a doubled word. The device becomes a tic and the emphasis flattens.',
   'epizeuxis,epimone,antanaclasis,polyptoton',
   'polyptoton,epistrophe',
   'Conduplicatio and antanaclasis are the same shape with different content: one repeats the word to keep its meaning, the other to break it. Chapter 1''s "etc." holds both.'),

  ('diacope','Interrupted Repetition','diacope (Greek: dia, through + koptein, to cut)',
   'Greek diakope, a cutting in two: the repetition cut through by a word.',
   'A word repeated with one or two small words wedged between the instances.',
   'A x A',
   'epizeuxis (no gap at all); epanalepsis (the gap is a whole clause)',
   'The intervening word is heard as an intensifier without having to be one, because the repetition brackets it.',
   1, 1,
   'When you want emphasis that still sounds like speech rather than declamation.',
   'Gives weight to a word while keeping the sentence conversational.',
   'Feeling admitted but controlled.',
   'Saying something true with force in a room where undisguised repetition would look staged.',
   'Smuggling an unearned intensifier into the bracket, so the strength of the feeling substitutes for the strength of the case.',
   'Strip the middle word out. Does the claim still stand up?',
   'It appears wherever you feel strongly, which means it marks your temperature rather than your point.',
   'epizeuxis,epanalepsis,epimone',
   'anaphora,erotema',
   'Diacope is the same yoke as epizeuxis with one word forced inside it. Part I is entirely this: one operation -- repetition or its absence -- applied at varying distances.'),

  ('anaphora','Anaphora','anaphora (Greek: ana, back + pherein, to carry)',
   'Greek anaphora, a carrying back: each clause carries the ear back to the same beginning.',
   'The same word or words at the start of successive clauses or sentences.',
   'A... / A... / A...',
   'tricolon (three such clauses, the strongest count); auxesis (the clauses grow in force)',
   'A repeated opening builds a pattern the listener starts to expect, so each new clause arrives pre-accepted and the differences at the end land hardest.',
   1, 2,
   'When you need a listener to remember the shape of what you said tomorrow, not just agree with it now.',
   'Turns a list into a structure and makes it memorable.',
   'Building pressure; momentum that feels like inevitability.',
   'Setting out several genuine reasons so their common source is audible.',
   'Manufacturing the FEELING of accumulated proof from three weak items in a row, because the pattern supplies the conviction the content lacks.',
   'Count the clauses, then weigh them separately. Would any one of them convince me on its own?',
   'Three-part lists in ordinary conversation; someone else adopting your cadence to mock it.',
   'epistrophe,symploce,epimone,isocolon',
   'isocolon,polysyndeton,tricolon',
   'Anaphora only reads as anaphora because the ear has already accepted the pattern. This is why Part III is unusable until Parts I and II are installed: a gap registers only against an established pattern.'),

  ('epistrophe','Epistrophe','epistrophe (Greek: epi, upon + strephein, to turn)',
   'Greek epistrophe, a turning about: each clause turns back onto the same ending.',
   'The same word or words at the end of successive clauses or sentences.',
   '...A / ...A / ...A',
   'antistrophe (the same figure under its other classical name); epiphora',
   'The last word of a clause is the one the ear keeps. Landing repeatedly on one word makes it the residue of the whole passage.',
   1, 3,
   'When one word must be what the listener is left holding after everything else fades.',
   'Deposits a single term as the conclusion of several different lines of thought.',
   'Finality. Each clause closes like a door.',
   'Showing that several separate considerations genuinely converge on one answer.',
   'Driving unrelated clauses to the same terminal word so convergence is performed rather than demonstrated.',
   'Did these clauses arrive at that word, or were they steered to it?',
   'Your sentences all end on the same beat; the pattern is audible as technique.',
   'anaphora,symploce,anadiplosis',
   'anaphora,isocolon,asyndeton',
   'Anaphora and epistrophe are one figure viewed from the two ends of a clause. Chapter 4 then shows what happens when you refuse to choose between them.'),

  ('symploce','Symploce','symploce (Greek: sym, together + plekein, to weave)',
   'Greek symploke, an interweaving: both ends held while the middle is free.',
   'Anaphora and epistrophe at once: the same opening AND the same ending, with only the middle changing.',
   'A...B / A...B / A...B',
   'anaphora alone; epistrophe alone; the frame-and-variable pattern',
   'Fixing both ends turns the sentence into a frame, and everything the listener notices is what changed in the middle. Comparison becomes involuntary.',
   1, 4,
   'When you want a theme bound tight and the listener doing the comparison for you.',
   'Isolates the variable by locking the constants.',
   'Inevitability, and a faint sense of being closed in.',
   'Comparing options honestly on one axis, holding everything else fixed so the real difference shows.',
   'Holding the frame fixed while the items inside are not actually comparable, so a false equivalence is presented as arithmetic.',
   'Are the things in the middle genuinely the same kind of thing?',
   'It sounds written. Symploce almost never survives in real speech without being noticed.',
   'anaphora,epistrophe,isocolon,polyptoton',
   'isocolon,chiasmus',
   'Symploce is not a third figure; it is Chapters 2 and 3 refusing to be separate. Book 11.7 pairs it with polyptoton as the two figures that bind a theme.'),

  ('anadiplosis','Anadiplosis','anadiplosis (Greek: ana, again + diploos, double)',
   'Greek anadiplosis, a doubling back: the end of one clause becomes the start of the next.',
   'The last word of one clause is repeated as the first word of the next.',
   '...A / A...',
   'gradatio or climax (the doubling repeated in a chain: A-B, B-C, C-D)',
   'The listener cannot let the word go, because it is handed forward into the next clause before the previous one has settled. It builds a chain that feels causal even when it is only sequential.',
   1, 5,
   'When you need suspense, or want a consequence to feel like it followed rather than was asserted.',
   'Links clauses so tightly they read as a single argument advancing.',
   'Mounting tension; the sense of something being tracked to its end.',
   'Making a genuine causal chain audible so each step can be checked.',
   'Manufacturing a causal chain out of mere adjacency: the grammar supplies the "therefore" that the reasoning never earned.',
   'Replace each link with the word "therefore". Does every step survive it?',
   'Every explanation becomes a chain. Also: chains longer than three links, which nobody speaks and everybody notices.',
   'gradatio,epistrophe,anastrophe,polyptoton',
   'anastrophe,polysyndeton',
   'Anadiplosis is the seed of gradatio, and gradatio is one of the devices Chapter 1''s "etc." conceals. Book 11.7 pairs it with anastrophe as the two suspense figures.'),

  ('polyptoton','Polyptoton','polyptoton (Greek: poly, many + ptosis, case)',
   'Greek polyptoton, many cases: one root appearing in several grammatical forms.',
   'The same root word repeated in a different grammatical form -- noun to verb, singular to plural, tense to tense.',
   'A(root) in form 1 ... A(root) in form 2',
   'antanaclasis (the same word, a different meaning); ploce; changes of the verb, a form Farnsworth treats separately',
   'Repetition the ear registers but the mind does not classify as repetition, so emphasis arrives without any sense of being repeated at.',
   1, 6,
   'When a theme must be bound without the binding being noticed.',
   'Emphasis that stays invisible; the root saturates the sentence.',
   'Wit, and a suggestion of exactness.',
   'Showing that two things share a root when they genuinely do, which is often the whole argument.',
   'Implying a shared root means a shared nature -- treating an accident of vocabulary as evidence about the world.',
   'Does the shared root reflect something real, or only how the language happens to be built?',
   'Cleverness that draws attention to the speaker. The moment the listener admires the construction, it has failed.',
   'antanaclasis,conduplicatio,symploce,epizeuxis',
   'symploce,chiasmus,isocolon',
   'Polyptoton is the first figure in the book whose repetition can go completely undetected. That is the transition Part I ends on, and it is why the book can afford Part III at all.');

-- ===========================================================================
-- PART II -- WHAT YOU DO TO SENTENCES.
-- ===========================================================================
INSERT OR IGNORE INTO figures (
  slug, canonical_name, classical_name, etymology, plain_definition,
  structural_formula, sub_variants, mechanism, part, chapter_id,
  conversational_job, rhetorical_effect, emotional_effect, legitimate_use,
  manipulative_misuse, detection_question, overuse_tells, related_figures,
  stackable_with, hidden_layer
) VALUES
  ('isocolon','Isocolon','isocolon (Greek: isos, equal + kolon, member)',
   'Greek isokolon, of equal members: clauses cut to the same length.',
   'Successive clauses of matching length and parallel construction.',
   '[x x x] [x x x]',
   'bicolon (two members); tricolon (three); homoioteleuton (matched endings as well as lengths)',
   'Matched length reads as matched importance. The symmetry is a claim about the content, made by the rhythm rather than the words.',
   2, 7,
   'When two things must be weighed as equals, or a sentence must sound decided.',
   'Balance; the sound of a settled judgement.',
   'Poise, and confidence that does not need to be asserted.',
   'Presenting genuinely comparable alternatives with the symmetry the comparison deserves.',
   'Making an unequal pair sound equal -- balancing a real cost against a trivial one and letting the rhythm hide the difference.',
   'Are these two halves actually the same weight, or only the same length?',
   'Speech that scans. If a listener could set it to a metronome, they have noticed.',
   'chiasmus,symploce,anaphora,homoioteleuton',
   'anaphora,epistrophe,chiasmus,asyndeton',
   'Isocolon is where the book stops working on words and starts working on shapes. Every figure after it is a shape argument: the structure asserts something the words do not.'),

  ('chiasmus','Chiasmus','chiasmus (Greek: chiazein, to mark with a chi, the letter X)',
   'Greek chiasmos, a placing crosswise, from the letter chi -- the crossing itself is the diagram.',
   'Two ideas stated, then restated in reverse order.',
   'A B / B A',
   'antimetabole (the reversal uses the same words, not merely the same ideas)',
   'The reversal completes a shape the mind was already holding open, and the closure is felt as agreement. The satisfaction is structural, not logical.',
   2, 8,
   'When a relation must be shown to run both ways, or a claim must be turned back on the person who made it.',
   'Reversal; the sound of an argument closing on itself.',
   'Satisfaction, and the sense that something has been proved.',
   'Showing a real symmetry, where the reverse genuinely holds as well as the forward form.',
   'The most seductive misuse in the book: reversing terms whose relation is not symmetrical, so the shape delivers a proof the logic never supplied.',
   'Does the reversed half stand up on its own if the pretty version is stripped away?',
   'It is quotable. If it sounds like something that should be on a poster, it will be heard as performance.',
   'antimetabole,isocolon,symploce,anastrophe',
   'isocolon,symploce',
   'Chiasmus is the clearest case of the book''s real subject: structure making a claim. Antimetabole hides inside it and is the sharper of the two, which is why the chapter can be read as being about one figure when it is about two.'),

  ('anastrophe','Anastrophe','anastrophe (Greek: ana, back + strephein, to turn)',
   'Greek anastrophe, a turning upside down: the expected order inverted.',
   'Words placed out of their normal order, most often by moving to the front what would ordinarily come last.',
   'B A (where A B is expected)',
   'hyperbaton (a wider separation of words that belong together); inversion',
   'Delay. Holding back the expected word makes the listener wait, and what they were waiting for arrives with the weight of the waiting attached.',
   2, 9,
   'When one word must arrive last and land, or when a sentence needs to slow down without getting longer.',
   'Suspense inside a single sentence.',
   'Gravity, sometimes formality, occasionally archaism.',
   'Putting the genuinely important word in the position where it will be heard.',
   'Using strangeness of order to make an ordinary claim sound weighty or ancient, borrowing authority from syntax.',
   'Put the sentence back in normal order. Is it still worth saying?',
   'Speech that sounds translated. Anastrophe ages badly and is noticed instantly in casual talk.',
   'hyperbaton,anadiplosis,ellipsis',
   'anadiplosis,aposiopesis,isocolon',
   'Anastrophe and anadiplosis are Book 11.7''s suspense pair, and hyperbaton is anastrophe stretched -- another of the devices concealed in Chapter 1''s "etc."'),

  ('polysyndeton','Polysyndeton','polysyndeton (Greek: poly, many + syndeton, bound together)',
   'Greek polysyndeton, much bound together: a conjunction at every joint.',
   'A conjunction placed between every item in a series, where one at the end would do.',
   'A and B and C and D',
   'the paired-conjunction form (both ... and ... and); repetition of a preposition instead of a conjunction',
   'Every conjunction is a small pause that gives each item its own moment, so a list stops being a list and becomes an accumulation with no visible end.',
   2, 10,
   'When a quantity must be felt rather than counted.',
   'Weight and abundance; a series that seems to keep arriving.',
   'Fullness, sometimes exhaustion, sometimes dread.',
   'Making the real scale of something audible when a bare count would understate it.',
   'Inflating a short list into an apparent flood, so three items feel like a pattern and a pattern feels like proof.',
   'Count the items. Is the number as impressive as the sentence made it sound?',
   'Long sentences that keep going and going, which is exactly the tell -- the device announces itself by construction.',
   'asyndeton,anaphora,isocolon',
   'anaphora,isocolon,epistrophe',
   'Polysyndeton and asyndeton are the same chapter split in two: excess of joints, then absence of them. Book 11.7 gives polysyndeton to cadence and asyndeton to energy.'),

  ('asyndeton','Asyndeton','asyndeton (Greek: a-, without + syndeton, bound together)',
   'Greek asyndeton, unbound: the conjunctions removed.',
   'Conjunctions omitted from a series, leaving the items bare against each other.',
   'A, B, C',
   'brachylogia (conjunctions dropped between single words); the paratactic list',
   'Removing the joints removes the pauses. The list arrives faster than it can be assessed, and speed reads as certainty.',
   2, 11,
   'When you want energy and finality, and no time given for objections between items.',
   'Speed; the sound of someone who has finished deliberating.',
   'Decisiveness, force, sometimes coldness.',
   'Delivering a conclusion already reached, where deliberation would misrepresent your actual state.',
   'Using speed to prevent examination -- the listener has agreed to the whole series before they could weigh any part of it.',
   'Put the conjunctions back in and read it slowly. Do I still agree with every item?',
   'Clipped speech across a whole conversation. Sustained asyndeton reads as either theatrical or hostile.',
   'polysyndeton,brachylogia,ellipsis',
   'epistrophe,isocolon,aposiopesis',
   'Asyndeton is the book''s first figure of ABSENCE, and it works only because the conjunctions were expected. Part I established the patterns; Part II begins removing them, which is the whole architecture of the book.'),

  ('ellipsis','Ellipsis','ellipsis (Greek: en, in + leipein, to leave)',
   'Greek elleipsis, a falling short: something left out and supplied by the listener.',
   'A word or phrase omitted because the listener can reconstruct it from what came before.',
   'A does X; B [does] Y',
   'zeugma and syllepsis (one word governing two others, only one grammatically); aposiopesis (the omission is a breaking off)',
   'The listener completes the sentence, and what a person supplies themselves they do not argue with. Consent is manufactured by participation.',
   2, 12,
   'When you want the listener to finish the thought and thereby own it.',
   'Compression, and the intimacy of shared understanding.',
   'Complicity; the sense of not needing things spelled out.',
   'Trusting a listener with what they already know, instead of talking down to them.',
   'Omitting the part of the claim that would not survive being said out loud, and letting them fill it in with their own worst assumption.',
   'What exactly did I supply, and would I have accepted it if it had been stated?',
   'Sentences a stranger could not parse. Ellipsis fails silently: the listener does not object, they simply reconstruct something else.',
   'zeugma,aposiopesis,asyndeton,brachylogia',
   'asyndeton,anastrophe,aposiopesis',
   'Ellipsis is the hinge of the entire book. Parts I and II built patterns; ellipsis proves the listener will complete one. Every figure in Part III is a controlled application of that fact, which is why Part III cannot be used first.');

-- ===========================================================================
-- PART III -- WHAT YOU DO TO THE LISTENER.
-- Usable only after Parts I and II: every figure here is a controlled ABSENCE,
-- and a gap registers only against a pattern the listener has already accepted.
-- ===========================================================================
INSERT OR IGNORE INTO figures (
  slug, canonical_name, classical_name, etymology, plain_definition,
  structural_formula, sub_variants, mechanism, part, chapter_id,
  conversational_job, rhetorical_effect, emotional_effect, legitimate_use,
  manipulative_misuse, detection_question, overuse_tells, related_figures,
  stackable_with, hidden_layer
) VALUES
  ('praeteritio','Praeteritio','praeteritio (Latin: praeterire, to pass by)',
   'Latin praeteritio, a passing over: the thing raised in the act of declining to raise it.',
   'Announcing that you will not mention something, thereby mentioning it.',
   'I will not speak of X. [X is now in the room.]',
   'apophasis (denying that one is saying what one is saying); occultatio; paralipsis',
   'A negation cannot be processed without first entertaining what is negated. The listener must hold the thing in mind in order to be told it is being set aside, and the setting-aside does not remove it.',
   3, 13,
   'When something must be present in the conversation but you cannot be the one who put it there.',
   'Introduces material while appearing to withhold it.',
   'Restraint on the surface; suggestion underneath.',
   'Genuinely declining to pursue a point while being honest that it exists, which is sometimes the only fair thing to do.',
   'The nastiest figure in the book. It plants an accusation and keeps the deniability, because the speaker never made the claim and cannot be asked to support it.',
   'What was I just made to think about, and did the speaker take any responsibility for it?',
   'Any use at all in a personal relationship. It is heard as exactly what it is, and it is remembered.',
   'litotes,aposiopesis,prolepsis,ellipsis',
   'aposiopesis,litotes',
   'Praeteritio is ellipsis aimed on purpose: the listener supplies the omitted content, and the speaker keeps clean hands. Part III opens here because this is the plainest demonstration that a gap does work.'),

  ('aposiopesis','Aposiopesis','aposiopesis (Greek: apo, away + siopan, to be silent)',
   'Greek aposiopesis, becoming silent: the sentence broken off unfinished.',
   'Stopping mid-sentence and leaving the rest unsaid.',
   'A --',
   'reticentia; the interrupted threat; the trailing concession',
   'An unfinished sentence is the strongest form of ellipsis, because the listener completes it with whatever they most expect -- usually something worse than you would have said.',
   3, 14,
   'When stopping is stronger than continuing, and when what they imagine exceeds what you could state.',
   'Maximum implication from minimum commitment.',
   'Anything from real emotion overtaking speech to unmistakable menace.',
   'Stopping because continuing would be cruel, unwise, or untrue -- and being visibly willing to stop.',
   'Manufactured menace: an implied threat that was never made, so it cannot be answered, withdrawn, or held against you.',
   'What did I fill in, and did they ever actually say it?',
   'Trailing off more than once. A single break is speech; a habit of breaks is a performance, and it invites the listener to test whether anything follows.',
   'praeteritio,ellipsis,metanoia,asyndeton',
   'asyndeton,anastrophe,epizeuxis',
   'Aposiopesis is ellipsis with the omission moved to the end and made audible. Book 11.7 gives it the single job of stopping short, and stopping short only works where a pattern of finishing has been established.'),

  ('metanoia','Metanoia','metanoia (Greek: meta, after + noos, mind)',
   'Greek metanoia, an afterthought or change of mind: the correction made in public.',
   'Saying something, then visibly correcting or qualifying it in the same breath.',
   'A -- or rather, B',
   'correctio; epanorthosis; the retracted overstatement',
   'A visible self-correction proves the speaker is monitoring their own accuracy, and that display of scruple transfers credibility to everything around it -- including the revision, which is never itself examined.',
   3, 15,
   'When precision matters and you want the listener to see you paying for it.',
   'Makes the final formulation feel hard-won rather than asserted.',
   'Honesty, care, thinking happening in real time.',
   'Actually correcting yourself when the first formulation was wrong. This is the figure that is best when it is not a figure at all.',
   'Staging the correction: the first version is put there to be withdrawn, so the second arrives wearing borrowed integrity and is accepted without scrutiny.',
   'Was the first version a real error, or was it built to be corrected?',
   'A pattern of corrections that always land on a stronger claim. Genuine self-correction sometimes weakens what you said.',
   'aposiopesis,litotes,prolepsis',
   'litotes,hypophora',
   'Metanoia is the only figure in the book that works by exhibiting the machinery. Book 11.9 makes it the sharpest self-audit case, because the same move is honesty or theatre depending on nothing the listener can see.'),

  ('litotes','Litotes','litotes (Greek: litos, plain, simple)',
   'Greek litotes, plainness: understatement, often by denying the opposite.',
   'Deliberate understatement, frequently by negating the contrary.',
   'not un-X',
   'meiosis (belittling); the double negative; the English habit of "not bad"',
   'Understatement asks the listener to supply the real magnitude, and a magnitude someone arrives at themselves is one they trust. Restraint also reads as having reserves.',
   3, 16,
   'When calm is the message, and when a full statement would sound like pleading.',
   'Force through restraint; the sound of a strong position not needing to be pressed.',
   'Composure. Occasionally, controlled contempt.',
   'Refusing to inflate something, especially your own case, when the facts do the work unaided.',
   'False modesty that fishes for the listener to overstate on your behalf, or a serious harm minimised into acceptability -- understatement used to shrink a real cost.',
   'If this were said plainly, would the size of it still be acceptable?',
   'Everything is "not ideal". Habitual litotes reads as evasion, and eventually as insincerity.',
   'meiosis,praeteritio,metanoia',
   'praeteritio,isocolon',
   'Litotes is controlled absence applied to magnitude rather than to words: the size is the thing withheld. Book 11.7 assigns it the single job of calm.'),

  ('erotema','Rhetorical Question','erotema (Greek: erotan, to ask)',
   'Greek erotema, a question: asked without wanting an answer.',
   'A question asked for effect, whose answer is already established or obvious.',
   'Q? [no answer sought]',
   'epiplexis (reproachful questioning); anacoenosis (asking the audience to judge); aporia (feigned doubt)',
   'A question compels the listener to answer internally. Having answered it themselves, they hold the conclusion as their own rather than as yours.',
   3, 17,
   'When pressure must be applied without an accusation being made.',
   'Turns a claim into the listener''s own conclusion.',
   'Pressure. Depending on delivery: invitation, or indictment.',
   'Inviting someone to reach a conclusion you believe they will reach honestly, and leaving them room to reach a different one.',
   'A closed question with an accusation loaded in the premise, so answering at all concedes the frame -- and refusing to answer looks evasive.',
   'What does answering this question concede before I have said anything?',
   'Questions you do not want answered, asked repeatedly. Also: asking one and then answering it yourself, which is a different figure and the listener notices the switch.',
   'epiplexis,hypophora,anacoenosis,prolepsis',
   'anaphora,hypophora,epizeuxis',
   'Erotema is the point where the book stops arranging your sentence and starts arranging the listener''s. The next two chapters are corrections to it: hypophora answers the question, prolepsis pre-empts theirs.'),

  ('hypophora','Hypophora','hypophora (Greek: hypo, under + pherein, to carry)',
   'Greek hypophora, a carrying under: the question raised and then carried by the speaker.',
   'Asking a question and immediately answering it yourself.',
   'Q? A.',
   'anthypophora (the reply proper); ratiocinatio; the self-posed objection',
   'Whoever frames the question owns the terms of the answer. Asking it yourself means the listener receives your answer as a response rather than as a claim -- and responses are examined far less than claims.',
   3, 18,
   'When you need to own the frame of a discussion without appearing to control it.',
   'Sets the agenda while sounding responsive.',
   'Command, clarity, the sense of a speaker in control of the ground.',
   'Raising the question the listener actually has and answering it straight, which is simply good exposition.',
   'Asking an easy version of a hard question -- answering the objection nobody raised so the real objection now seems addressed and out of order to bring up.',
   'Is that the question I would have asked, or a friendlier one standing in for it?',
   'Whole conversations conducted in your own questions. It reads as lecturing, and it stops the other person speaking.',
   'erotema,prolepsis,anacoenosis',
   'erotema,anaphora,isocolon',
   'Hypophora is erotema with the gap filled by the speaker rather than the listener. Book 11.7 assigns it the job of owning the frame, and framing is what the whole of Part III is about.'),

  ('prolepsis','Prolepsis','prolepsis (Greek: pro, before + lambanein, to take)',
   'Greek prolepsis, an anticipating: the objection taken up before it is made.',
   'Raising and answering an objection before the other person can raise it.',
   'You will say X. But Y.',
   'procatalepsis; anticipatio; the pre-emptive concession',
   'An objection you voice first arrives without the force of opposition attached. It is also disarming in the literal sense: the listener discovers you have already thought about their side.',
   3, 19,
   'When an objection is coming and you would rather meet it than defend against it.',
   'Removes the other side''s strongest move by making it yours.',
   'Fairness, confidence, and the sense of having been anticipated.',
   'Stating their real objection at full strength and answering it honestly -- including admitting where it holds.',
   'The straw pre-emption: voicing a weakened version of their objection and defeating that, so the strong version now looks like a repeat of a settled point.',
   'Is that my actual objection, stated at its strongest, or a version built to lose?',
   'Answering objections nobody had. It signals defensiveness and tells the listener where you are worried.',
   'hypophora,erotema,praeteritio,metanoia',
   'hypophora,isocolon,litotes',
   'Prolepsis is the book''s last figure because it operates on a pattern that exists only in the listener''s head. Book 11.1''s root node holds: this too is controlled absence -- the absence of the objection, removed before it was spoken.');

